name: newsify
description: "Your Local Newswala."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^1.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  path_provider: ^2.0.15
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.2.1
  # share_plus: ^7.2.2
  share_plus: ^10.1.4
  webview_flutter: ^4.4.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# App Icon Configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/app/app_logo.png
    - assets/badges/playstore_badge.png
    - assets/badges/appstore_badge.png